### ISSUE TITLE
[feat]: show location preview with telescope.nvim 

### ISSUE THREAD

**Issue by benwoodward** [eckon/treesitter-current-functions#12]
So glad this exists, thanks for building it. I switched from using `:Telescope lsp_document_symbols` because it doesn't recognise JS arrow functions as functions. 

What I'm missing after switching is a preview of function's location in the file, which helps you get context when you're darting around a file.

**Comment by eckon** [comment]
Hey @benwoodward , thanks for the nice issue/comment :)

Yeah I originally planned some preview as well. The main reason its not yet implemented is, that I mainly wanted to focus on basic features, and the preview is really dependent on the different selectors (fzf, telescope, etc.).

But as I also switched mainly to telescope I dont mind trying it out for telescope (if others want it for other parts, then Im always open for PRs).

So far I tried playing around with it, but am a bit stuck at showing the correct line that would be jumped to. I hope I can bring some good news soon.
If you have any knowledge on how to highlight or move the preview on the correct line, feel free to direct me to the resources.

![image](https://github.com/eckon/treesitter-current-functions/assets/40291209/480fa0ad-d1f6-49de-9743-9fcc0a48a7e8)

**Comment by eckon** [comment]
@benwoodward okay, I think im happy enough with this result. Hope this helps you as well :)

here a small example
![telescope-preview-example](https://github.com/eckon/treesitter-current-functions/assets/40291209/d901f657-b572-491c-b3ca-27bd41bf3edb)

**Comment by benwoodward** [comment]
fantastic! thanks. 

is is possible to configure the layout to be side by side, or is that a telescope.nvim config?

**Comment by eckon** [comment]
Unless I missed some default values that needs to be passed, this should work by setting default telescope options.

Mainly as what you see are my default settings, I did not add any layout settings in this plugin.

EDIT: yes the telescope strategy handles this

here an example with "horizontal" instead of "vertical" and im pretty sure you can customize it even more, but then you need to look into telescope

for example: https://github.com/eckon/dotfiles/blob/master/config/nvim/lua/eckon/plugins/telescope.lua#L18
```lua
require("telescope").setup({
    defaults = {
      -- ...
      layout_strategy = "horizontal",
      -- ...
    },
```

![image](https://github.com/eckon/treesitter-current-functions/assets/40291209/6946d969-d254-43ec-9ad5-364820f09549)
